"""Checklist for live EPAS v3.2 acceptance against a real Supabase project."""
CASES = [
    'ROLE_GM_PROJECT_AND_CERTIFICATE',
    'ROLE_DM_ASSIGNMENT_AND_VERIFICATION',
    'ROLE_ENGINEER_APPRAISAL_AND_ARTIFACTS',
    'ROLE_SURVEYOR_ACCEPT_SCOPE_DRAWINGS_CHECKLIST_EXECUTE_REPORT',
    'ROLE_DESIGNER_SUBMIT_CORRECT_REVISE',
    'ROLE_SHIPYARD_NSC_ONLY',
    'ROLE_OWNER_INSERVICE_ONLY',
    'ROLE_SHIP_MANAGEMENT_INSERVICE_AND_CORRECTIVE',
    'RLS_CROSS_PROJECT_ISOLATION',
    'STORAGE_CROSS_PROJECT_ISOLATION',
    'STAKEHOLDER_PHASE_ISOLATION',
    'SESSION_JWT_ISOLATION',
    'CERTIFICATE_UPLOAD_ROLLBACK',
    'SCHEDULER_CRON_EXECUTION',
    'INSERVICE_CYCLE_1_TO_CYCLE_2',
    'LARGE_FILE_CONCURRENCY',
]

if __name__ == '__main__':
    print('EPAS v3.2 live acceptance cases:')
    for case in CASES:
        print(f'- {case}')
